### PR TITLE
Convert Readme to markdown

### PR DESCRIPTION
**Pull request by EwoutH**
Converts the Readme to markdown syntax, which allows more styling, hyperlinking and better default rendering by GitHub.

### CODE REVIEW

**Comment by aescolar** [comment]
Hi @EwoutH , the branch this PR is targeting (sneak_peek) is a snapshot of a different project repository. So no PRs will be merged against it.
This repository is not really yet a Zephyr module, or a module one can work against.
A separate branch would need to be created here for that.
The same applies to #2

**Comment by EwoutH** [comment]
Thanks for your reply! Feel free to merge these two PRs into the private repository for now.

Could you explain a bit what the general context and plan/roadmap is for liblc3codec? I'm very interested in getting LC3 support implemented on major platforms and this looks like (one of) the first open source implementations!

**Comment by aescolar** [comment]
>Feel free to merge these two PRs into the private repository for now.

Thanks. Note that for any commit to be mergeable into a Zephyr repo it needs to follow the Zephyr contribution guidelines (in this case, it needs to be signed off: https://docs.zephyrproject.org/latest/contribute/index.html#developer-certification-of-origin-dco ).

This repository was created due to the interest from the Zephyr project members to access the EHIMA LC3 codec before the time in which it was meant to be released and made public as part of the project it originally targets.
As such, in Zephyr, I don't think there is yet any concrete plan on how to use it yet.

**Comment by EwoutH** [comment]
Thanks for the info!

I added Signed-off info to the commit messages, if you have any interest in merging them (please note they are also signed and verified by GitHub with my GPG key).

**Comment by Casper-Bonde-Bose** [comment]
Hi @EwoutH 
A new more optimized version of the LC3 codec were added to the Zephyr project in the branch called zephyr. As this repo is a clone of external source we should do minimal changes to it - and preferably none. I'll be deleting the sneak_peak branch, hence also this PR.
If changes are to be made to the source code they should be done in the repository where the Zephyr code is cloned from - which is Android for now. Android recently moved the code to a public github repo (https://github.com/google/liblc3) and we still have a task to update Zephyr to use the code from this new location. But a license discussion started by Intel needs to be resolved first.

**Pull request closed without merging**
